module.exports = {
  policy: {
    directives: {
      'default-src': ['self', 'blob:'],
      'style-src': ['self', 'unsafe-inline', 'https:'],
      'font-src': [
        'self',
        'https://fonts.gstatic.com',
        'https://ka-f.fontawesome.com/',
      ],
      'script-src': [
        'self',
        'unsafe-inline',
        'data',
        'blob:',
        'https://js.stripe.com',
        'https://*.mapbox.com',
        'https://*.cloudflare.com/',
        'https://bundle.js:8828',
        'ws://localhost:56558/',
        'https://cdn.jsdelivr.net/',
        'https://kit.fontawesome.com/',
      ],
      'frame-src': [
        'self',
        'unsafe-inline',
        'data:',
        'blob:',
        'https://*.stripe.com',
        'https://*.mapbox.com',
        'https://*.cloudflare.com/',
        'https://bundle.js:*',
        'ws://localhost:*/',
      ],
      'img-src': [
        'self',
        'unsafe-inline',
        'data:',
        'blob:',
        'https://*.stripe.com',
        'https://*.mapbox.com',
        'https://*.cloudflare.com/',
        'https://bundle.js:*',
        'ws://localhost:*/',
        'https://res.cloudinary.com/',
      ],
      'connect-src': [
        'self',
        'unsafe-inline',
        'data:',
        'blob:',
        `wss://bjorns-portfolio-api.herokuapp.com:${process.env.PORT}/`,
        'https://*.stripe.com',
        'https://*.mapbox.com',
        'https://*.cloudflare.com/',
        'https://bundle.js:*',
        'ws://localhost:*/',
        'https://ka-f.fontawesome.com/',
      ],
      'load-src': ['blob:'],
    },
  },
};
